name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

categories:
  - title: 'Enhancement'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Dependencies'
    label: 'dependencies'
  - title: 'Pipeline'
    label: 'pipeline'

version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: enhancement'
  patch:
    labels:
      - 'type: bug'
      - 'type: docs'
      - 'type: dependencies'
  default: patch
